Задание 6. Добавлена операция регистрации нового пользователя
gpb-it-factory/gladskoy-middle-service pull request #15
Opened 2024-05-28 11:33 UTC by saneci

2024-06-03 09:20 UTC, vaganov-vadim commented
Привет! Сорри, что долго, куча МРок навалилась и лекций) Постараюсь в ближайшее время посмотреть.

2024-06-03 12:03 UTC, saneci commented
> Привет! Сорри, что долго, куча МРок навалилась и лекций) Постараюсь в ближайшее время посмотреть.

@vaganov-vadim, привет! Изменил статус PR на "черновик", так как внёс изменения в структуру проекта: постарался сделать согласно [рекомендациям из лекции по архитектуре](https://github.com/gpb-it-factory/architecture).

2024-06-04 06:12 UTC, vaganov-vadim requested changes
Как всегда, отличная работа, молодчина! Посмотри пару моих комментов, может найдёшь что-то полезное для себя и проекта =)

2024-06-04 06:12 UTC, vaganov-vadim commented on build.gradle
> +tasks.register("backendServiceOpenApi", GenerateTask) {
Крутяк!

2024-06-04 06:12 UTC, vaganov-vadim commented on src/main/java/ru/gpbitfactory/minibank/middle/createclient/api/ClientsController.java
> +public class ClientsController {
У тебя всё круто, поэтому буду советовать уже какие-то более глубокие штуки или практики. По-хорошему, надо покрывать публичный API (и это не только REST API, а и просто публичные классы) javadoc'ами. Так новым разработчикам проще въезжать в проект :) Причём чаще всего javadoc должен отвечать на вопрос "для чего", а не "что", особенно если в реализации есть какие-то нюансы.
Это неблокирующий комментарий, просто на будущее может пригодиться =)

2024-06-04 06:12 UTC, vaganov-vadim commented on src/main/java/ru/gpbitfactory/minibank/middle/mockbackend/api/UsersMockApiClient.java
> +public class UsersMockApiClient implements UsersApiClient {
Как на счёт того, чтобы мок "поднимался" в соответствии с настройкой в application.yml? Что-то типа mock.enable. Чтобы это не попало случайно в "продакшн" код.

2024-06-04 06:12 UTC, vaganov-vadim commented on src/main/java/ru/gpbitfactory/minibank/middle/mockbackend/api/UsersMockApiClient.java
> +    @Override
Кстати, ещё один из вариантов подобных заглушек - wiremock или mockserver. Опять же не блокирует, но просто взгляни, вдруг понравится.

2024-06-04 11:52 UTC, saneci commented on build.gradle
> +tasks.register("backendServiceOpenApi", GenerateTask) {
Спасибо! 😊

2024-06-04 11:55 UTC, saneci commented on src/main/java/ru/gpbitfactory/minibank/middle/createclient/api/ClientsController.java
> +public class ClientsController {
> Это неблокирующий комментарий, просто на будущее может пригодиться =)

Попробую всё же сделать в этом PR. Как будет готово, пингану в этоv треде :)

2024-06-04 12:04 UTC, saneci commented on src/main/java/ru/gpbitfactory/minibank/middle/mockbackend/api/UsersMockApiClient.java
> +    @Override
Работал с этими инструментами ранее, крутые и удобные, применял их в ручном и авто-тестировании. В этом случае почему-то решил, что сделать заглушку в коде будет "правильнее" :) В будущем попробую применить эти инструменты, спасибо!

2024-06-04 12:07 UTC, saneci commented on src/main/java/ru/gpbitfactory/minibank/middle/mockbackend/api/UsersMockApiClient.java
> +public class UsersMockApiClient implements UsersApiClient {
Интересная идея, но пока не понимаю как это можно реализовать. Подумаю, если не получиться, тогда приду за помощью :)

2024-06-04 15:13 UTC, saneci commented on src/main/java/ru/gpbitfactory/minibank/middle/createclient/api/ClientsController.java
> +public class ClientsController {
@vaganov-vadim первая попытка сделать javadoc: https://github.com/gpb-it-factory/gladskoy-middle-service/pull/15/commits/2f3cc37ff451543e6fe350c348cac0412d328044

Жду обратной связи, правильно ли я вообще понял эту рекомендацию :)

2024-06-10 15:21 UTC, saneci commented on src/main/java/ru/gpbitfactory/minibank/middle/mockbackend/api/UsersMockApiClient.java
> +public class UsersMockApiClient implements UsersApiClient {
@vaganov-vadim пока не придумал как сделать с помощью `mock.enable`. Буду рад и очень благодарен за любую помощь.

2024-06-11 05:32 UTC, vaganov-vadim commented on src/main/java/ru/gpbitfactory/minibank/middle/mockbackend/api/UsersMockApiClient.java
> +public class UsersMockApiClient implements UsersApiClient {
Вот в эту сторону посмотри - https://www.baeldung.com/spring-conditionalonproperty
Если будут вопросы - пиши :)

2024-06-11 05:32 UTC, vaganov-vadim commented on src/main/java/ru/gpbitfactory/minibank/middle/createclient/api/ClientsController.java
> +public class ClientsController {
Всё отлично понял, кайф!

2024-06-11 05:33 UTC, vaganov-vadim approved these changes
@saneci добавил коммент про мок, но блокировать PR не буду, давай вливать, можешь доработать отдельно потом. Посмотри коммент, где незакрытое обсуждение - закрой и вливай.

2024-06-11 09:25 UTC, saneci commented on src/main/java/ru/gpbitfactory/minibank/middle/mockbackend/api/UsersMockApiClient.java
> +public class UsersMockApiClient implements UsersApiClient {
Завел на это отдельную задачу https://github.com/gpb-it-factory/gladskoy-middle-service/issues/18

2024-06-11 09:25 UTC, merged