Задание 5. Добавлен базовый CI
gpb-it-factory/gladskoy-middle-service pull request #7
Opened 2024-05-23 10:15 UTC by saneci

2024-05-27 15:41 UTC, konstantin-kozlovskiy commented on .github/workflows/gradle-ci.yml
> +        run: ./gradlew build
./gradlew build -x test , на билде тоже запускаются тесты, можно это исправить флагом -x

2024-05-27 15:44 UTC, konstantin-kozlovskiy requested changes
Мелкое исправление

2024-05-27 16:49 UTC, saneci commented on .github/workflows/gradle-ci.yml
> +        run: ./gradlew build
Исправлено https://github.com/gpb-it-factory/gladskoy-middle-service/pull/7/commits/946904648ec808e0d052cf8a983ae4744f010350

2024-05-28 12:19 UTC, konstantin-kozlovskiy approved these changes

2024-05-28 12:19 UTC, merged